# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Wolf Report
tagline:          ''
description:      ''
url:              http://michael-wolfenden.github.io
baseurl:          /

author:
  name:           'Michael Wolfenden'
  url:            https://twitter.com/m_wolfenden

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/michael-wolfenden/michael-wolfenden.github.io
