# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'The Wolf Report'
tagline:          ''
description:      'Handcrafted artisan links by <a href="https://github.com/michael-wolfenden/">Michael Wolfenden</a>'
url:              https://michael-wolfenden.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Michael Wolfenden'
  url:            https://github.com/michael-wolfenden

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-algolia
  
# Custom vars
sidebar_home_link:  false

google_analytics: UA-61219823-1

github:
  repo: https://github.com/michael-wolfenden/

feed:
  path: atom.xml
  
algolia:
  application_id: 'THE WOLF REPORT'
  index_name: jekyll
  search_only_api_key: 0e3cfa04f899b670107857e7c965f5c5
